ignored_colors = []
allowed_colors = ["6D001A","BE0039","FF4500","FFA800","FFD635","FFF8B8","00A368","00CC78","7EED56","00756F","009EAA","00CCC0","2450A4","3690EA","51E9F4","493AC1","6A5CFF","94B3FF","811E9F","B44AC0","E4ABFF","DE107F","FF3881","FF99AA","6D482F","9C6926","FFB470","000000","515252","898D90","D4D7D9","FFFFFF"]
width = 3000
height = 2000
add-x = 1500-1500
add-y = 1000-1500
default_prio = 120

[[structure]]
name = "swiss 1"
file = "swiss1.png"
disabled = false
startx = 1682-1500
starty = 632-1500
priority = 200
overlay_only = false

[[structure]]
name = "swiss 2"
file = "swiss2.png"
disabled = false
startx = 2296-1500
starty = 632-1500
priority = 200
overlay_only = false

[[structure]]
name = "swiss 3"
file = "swiss3.png"
disabled = false
startx = 901-1500
starty = 1184-1500
priority = 200
overlay_only = false